version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: symfony-nginx
    links:
      - php-fpm
      - php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-cli

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    container_name: symfony-php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    container_name: symfony-php-cli
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: symfony-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_USER=symfony"
      - "MYSQL_PASSWORD=symfony"
      - "MYSQL_DATABASE=symfony"

