version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: symfony-nginx
    links:
      - php-fpm
      - php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-cli

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    container_name: symfony-php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - manager-postgres
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    container_name: symfony-php-cli
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - manager-postgres
  mysql:
    image: mysql:5.7
    container_name: symfony-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_USER=symfony"
      - "MYSQL_PASSWORD=symfony"
      - "MYSQL_DATABASE=symfony"
  manager-postgres:
    image: postgres:11.2
    container_name: symfony-pgres
    volumes:
      - ./docker/manager-postgres:/var/lib/manager-postgres
    environment:
      POSTGRES_ROOT_PASSWORD: 123
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"

volumes:
  manager-postgres:
  composer: